version: '3'

services:
  api-server:
    image: docker.pkg.github.com/yasu-s/github-packages-test/test-server:1.0.0
    container_name: pkg-test-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
